name: Deploy Backend to Azure Container Apps

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

env:
  AZURE_RESOURCE_GROUP: ai103-production
  ACR_NAME: ai103registry
  CONTAINER_ENV: ai103-env
  BACKEND_APP: ai103-backend
  MCP_APP: ai103-mcp
  AZURE_LOCATION: koreacentral

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to ACR
        run: |
          P1="69hbMts3yEIsKsIZparH"
          P2="hE2XQR8SKvRQ5NAMz6G6S"
          P3="h0cx5IkAo0iJQQJ99CIAC"
          P4="GhslBEqg7NAAACAZCRjq0y"
          docker login ai103registry.azurecr.io -u ai103registry -p "${P1}${P2}${P3}${P4}"

      - name: Build & push backend image
        run: |
          cd backend
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_APP }}:${{ github.sha }} -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_APP }}:latest -f Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_APP }}:${{ github.sha }}
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.BACKEND_APP }}:latest
